#ifndef __LlFiles_H__
#define __LlFiles_H__

// Generated by OBNCPP 2019-04-09 on 2019-04-10T00:06:54

#include <Lolac/Ll_Global.h>

namespace Ll
{
	class Files : public _Root
	{
	public:
		static Files* _inst();
		Files();
		~Files();

		// TYPE
		typedef int /* unknown type */ File;
		typedef int /* unknown type */ Rider;

		static void Write(Files::Rider _0, char _1);
		Files::File New(int /* unknown type */ _0);
		static void Set(Files::Rider _0, Files::File _1, int _2);
		static void Register(Files::File _0);
	};
}

#endif // __LlFiles_H__