#ifndef __LlFiles_H__
#define __LlFiles_H__

// Generated by OBNCPP 2019-04-09 on 2019-04-10T00:06:54
// Modified by me@rochus-keller.ch on 2019-04-10

#include <Lolac/Ll_Global.h>
#include <fstream>

namespace Ll
{
	class Files : public _Root
	{
	public:
		static Files* _inst();
		Files();
		~Files();

		// TYPE
        struct FileDesc : public _Root // RK
        {
            std::ofstream d_file;
        };

        typedef FileDesc* File; // RK
        struct Rider    // RK
        {
            Rider():d_file(0){}
            File d_file;
        };

		static void Write(Files::Rider _0, char _1);
        Files::File New(_FxArray<char,128> _0); // RK
        static void Set(Files::Rider& _0, Files::File _1, int _2);
		static void Register(Files::File _0);
	};
}

#endif // __LlFiles_H__
