#ifndef __LlLSV_H__
#define __LlLSV_H__

// Generated by OberonViewer 0.6 on 2019-04-17T01:18:11

#include <Lolac/Ll_Global.h>
#include <Lolac/LlFiles.h>
#include <Lolac/LlTexts.h>
#include <Lolac/LlOberon.h>
#include <Lolac/LlLSB.h>

namespace Ll
{
	class LSV : public _Root
	{
	public:
		/* Lola System: display Verilog; generate txt-File; NW 27.8.2018 */
		static LSV* _inst();
		LSV();
		~LSV();

		// VAR
		Texts::Writer W;
		int nofgen;
		/* to avoid forward reference */
		void (*Constructor)(LSB::Item&);
		Files::File F;
		Files::Rider R;
		_FxArray<_FxArray<char,6>,64> C;

		// PROC
		static void Write(char ch);
		static void WriteLn();
		static void WriteInt(int x);
		static void WriteHex(int x);
		static void WriteString(_ValArray<char> s);
		static void Type(LSB::Type typ);
		static void BitArrLen(LSB::Type typ);
		static void Expression(LSB::Item x);
		static void Elem(LSB::Item& x);
		static void Constructor0(LSB::Item& x);
		static void Declaration(LSB::Object obj);
		static void ObjList0(LSB::Object obj);
		static void ActParam(LSB::Item& x, LSB::Object fpar);
		static void ObjList1(LSB::Object obj);
		static void ObjList2(LSB::Object obj);
		static void List(_ValArray<char> file);

	};
}

#endif // __LlLSV_H__