#ifndef __LlLSS_H__
#define __LlLSS_H__

// Generated by OBNCPP 2019-04-09 on 2019-04-10T00:06:54

#include <Lolac/Ll_Global.h>
#include <Lolac/LlTexts.h>
#include <Lolac/LlOberon.h>

namespace Ll
{
	class LSS : public _Root
	{
	public:
		/*  NW 16.10.93 / 13.8.2018 */
		static LSS* _inst();
		LSS();
		~LSS();

		// CONST
		static const int IdLen = 32;
		static const int NofKeys = 11;
		/* symbols */
		static const int null = 0;
		static const int arrow = 1;
		static const int times = 2;
		static const int div = 3;
		static const int and_ = 4;
		static const int plus = 5;
		static const int minus = 6;
		static const int or_ = 7;
		static const int xor_ = 8;
		static const int not_ = 9;
		static const int eql = 10;
		static const int neq = 11;
		static const int lss = 12;
		static const int leq = 13;
		static const int gtr = 14;
		static const int geq = 15;
		static const int at = 16;
		static const int apo = 17;
		static const int period = 18;
		static const int comma = 19;
		static const int colon = 20;
		static const int rparen = 21;
		static const int rbrak = 22;
		static const int rbrace = 23;
		static const int then = 24;
		static const int lparen = 26;
		static const int lbrak = 27;
		static const int lbrace = 28;
		static const int repl = 29;
		static const int becomes = 30;
		static const int integer_ = 31;
		static const int ident = 32;
		static const int ts = 33;
		static const int semicolon = 40;
		static const int end = 41;
		static const int const_ = 51;
		static const int type = 52;
		static const int reg = 53;
		static const int var = 54;
		static const int out = 55;
		static const int inout = 56;
		static const int in = 57;
		static const int begin = 58;
		static const int module = 59;
		static const int eof = 60;

		// TYPE
		typedef _FxArray<char,IdLen> Ident;

		// VAR
		int val;
		Ident id;
		bool error;
		char ch;
		int errpos;
		Texts::Reader R;
		Texts::Writer W;
		_FxArray<Ident,NofKeys> key;
		_FxArray<int,NofKeys> symno;

		// PROC
		static void Mark(_ValArray<char> msg);
		static void identifier(int& sym);
		static void Number(int& sym);
		static void comment();
		static void Get(int& sym);
		static void Init(Texts::Text T, int pos);

	};
}

#endif // __LlLSS_H__