#ifndef __LlLSP_H__
#define __LlLSP_H__

// Generated by OBNCPP 2019-04-09 on 2019-04-10T00:06:54

#include <Lolac/Ll_Global.h>
#include <Lolac/LlTexts.h>
#include <Lolac/LlOberon.h>
#include <Lolac/LlLSB.h>

namespace Ll
{
	class LSP : public _Root
	{
	public:
		/* display data structure;  NW 28.8.2015 */
		static LSP* _inst();
		LSP();
		~LSP();

		// VAR
		Texts::Writer W;
		_FxArray<_FxArray<char,6>,64> C;

		// PROC
		static void PrintType(LSB::Type typ);
		static void PrintTree(LSB::Item x, int n);
		static void PrintObj(LSB::Object obj, int n);
		static void List();

	};
}

#endif // __LlLSP_H__