#ifndef __LlOberon_H__
#define __LlOberon_H__

// Generated by OBNCPP 2019-04-09 on 2019-04-10T00:06:54

#include <Lolac/Ll_Global.h>

namespace Ll
{
	class Oberon : public _Root
	{
	public:
		static Oberon* _inst();
		Oberon();
		~Oberon();

		int /* unknown type */ Log;
		struct : public _Root {
			int /* unknown type */ pos;
			int /* unknown type */ text;
		} Par;
		static void GetSelection(Texts::Text _0, int _1, int _2, int _3);
	};
}

#endif // __LlOberon_H__