#ifndef __LlTexts_H__
#define __LlTexts_H__

// Generated by OBNCPP 2019-04-09 on 2019-04-10T00:06:54

#include <Lolac/Ll_Global.h>

namespace Ll
{
	class Texts : public _Root
	{
	public:
		static Texts* _inst();
		Texts();
		~Texts();

		// TYPE
		struct Reader;
		struct Writer;
		struct Scanner;

		struct Reader : public _Root {
			bool eot;
		};
		struct Writer : public _Root {
			int /* unknown type */ buf;
		};
		typedef int /* unknown type */ Text;
		struct Scanner : public _Root {
			int /* unknown type */ c;
			int /* unknown type */ class_;
			int /* unknown type */ s;
		};

		int /* unknown type */ Char;
		int /* unknown type */ Name;
		int /* unknown type */ String;
		static void OpenWriter(const Texts::Writer& _0);
		int Pos(const Texts::Reader& _0);
		static void WriteString(const Texts::Writer& _0, _ValArray<char> _1);
		static void WriteInt(const Texts::Writer& _0, int _1, int _2);
		static void WriteLn(const Texts::Writer& _0);
		static void Append(int /* unknown type */ _0, int /* unknown type */ _1);
		static void Read(const Texts::Reader& _0, char _1);
		static void OpenReader(const Texts::Reader& _0, Texts::Text _1, int _2);
		static void Write(const Texts::Writer& _0, _ValArray<char> _1);
		static void OpenScanner(const Texts::Scanner& _0, int /* unknown type */ _1, int /* unknown type */ _2);
		static void Scan(const Texts::Scanner& _0);
		static void Open(Texts::Text _0, int /* unknown type */ _1);
	};
}

#endif // __LlTexts_H__