#ifndef __LlTexts_H__
#define __LlTexts_H__

// Generated by OBNCPP 2019-04-09 on 2019-04-10T00:06:54
// Modified by me@rochus-keller.ch on 2019-04-10

#include <Lolac/Ll_Global.h>
#include <string>
#include <sstream>

namespace Ll
{
	class Texts : public _Root
	{
	public:
		static Texts* _inst();
		Texts();
        ~Texts();

		// TYPE
		struct Reader;
		struct Writer;
        struct TextDesc;

		struct Reader : public _Root {
            Reader():d_off(0),d_txt(0) {}
			bool eot;
            TextDesc* d_txt;
            int d_off;
        };
		struct Writer : public _Root {
            std::stringstream buf;
		};

        struct TextDesc : public _Root {
            std::string d_str;
        };
        typedef TextDesc* Text;

        static void OpenWriter(Texts::Writer& _0);
		int Pos(const Texts::Reader& _0);
        static void WriteString(Texts::Writer& _0, _ValArray<char> _1);
        static void WriteInt(Texts::Writer& _0, int _1, int _2);
        static void WriteLn(Texts::Writer& _0);
        static void Append(int /* unknown type */ _0, std::stringstream& _1);
        static void Read(Texts::Reader& _0, char& _1);
        static void OpenReader(Texts::Reader& r, Texts::Text _1, int off);
        static void Write(Texts::Writer& _0, _ValArray<char> _1);
        static void Open(Texts::Text text, _ValArray<char> path);
	};
}

#endif // __LlTexts_H__
